apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UuKIrYTZi8A6iomdZG84nq0R,iv:Uo1lHjBxLEs9yQlkCMPApsZ4enAlcGKyL/I49ysJOIA=,tag:eI9MTBczPA3S1eh4+IAaWg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:tbkAsEw6QjEyRJeJkWxtEHC6YrHEpeiiQYGQ9BF9KHJzir0jKQ==,iv:xYQIh7tOuWkKmVOgBFLxzvFH3LMKaNQzXMB1K7SxqyE=,tag:zV3CQFo3/heCgIX1ZOxvIw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:JzxQ8BCu3AkkYURs3Ijmkkvq,iv:wzI6m0P9X9BH1vqwYwVokiijZToKmcUr4G4GsVmYL3Y=,tag:dAWcHApDPxqgouFs0ZDeVA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpKzc3c0JRbjRTR1FTY3F0
            LzhWTVh2N0VXL3hNREUwRFRjZ3lSY2cwVG5jCnhDY0NrLzZaSmF2UC9CK25PODU3
            dmpmNGpleDh5Q1p5bjg1VUNRRVZVVncKLS0tIEVreDRRdEVWSG8zU050Z281cSs0
            TzVIQzFQbENqM3BsbEoxaE5YVE50TEEKQNZc1F4fElgZgSGS1jvbAEaG29iSx66v
            Nm4GxLJz5BoWvdSo/8r/Qsr/+owkAVQ6Ynx7rjmadf6lbuHlc6rBpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T06:27:58Z"
    mac: ENC[AES256_GCM,data:oQwHqeFWXBd+gTPEAMDRxYaMaT2DYsp92PDyhcg4EaYDQHujxQjbHxeLbj0zVZEVzHVFakiWoC7YEO7o5XWdWSUucSjcZU7sWhixlO3bpQ+MeiMZXQz9xsp5wGRO2uhyosRPKBqPlAZmt8/3LSc3dJAIbAZRErVUHDhf4P6ovKc=,iv:1Z5WKsi51VJWVYPsA107cJQgOrJsmw5GMoZt0GMJUag=,tag:T+J8a2TxBSqR8MRaqPc+pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
