---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-external-provisioner
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: gcr.io/k8s-staging-sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
    nfs:
      server: "10.10.100.191"
      path: "/mnt/pool-01/nfs"
    storageClass:
      defaultClass: false
      reclaimPolicy: Retain
      onDelete: retain
      accessModes: ReadWriteMany
