---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./bazarr/ks.yaml
  - ./overseerr/ks.yaml
  - ./plex/ks.yaml
  - ./prowlarr/ks.yaml
  - ./radarr/ks.yaml
  - ./radarr-anime/ks.yaml
  - ./recyclarr/ks.yaml
  - ./rtorrent-flood/ks.yaml
  - ./rtorrent-seed/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./sonarr/ks.yaml
  - ./sonarr-anime/ks.yaml
  - ./tautulli/ks.yaml
