---
creation_rules:
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
  - path_regex: terraform/.*\.sops\.ya?ml
    key_groups:
      - age:
          - age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
