---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./bitnami.yaml
  - ./bjw-s.yaml
  - ./democratic-csi.yaml
  - ./external-dns.yaml
  - ./goauthentik.yaml
  - ./hajimari.yaml
  - ./ingress-nginx.yaml
  - ./jameswynn.yaml
  - ./jetstack.yaml
  - ./k8s-at-home.yaml
  - ./k8s-gateway.yaml
  - ./kubernetes-dashboard.yaml
  # - ./loeken-at-home.yaml
  - ./metallb.yaml
  - ./metrics-server.yaml
  - ./nfs-subdir-external-provisioner.yaml
  - ./stakater.yaml
  - ./weave-gitops.yaml
