---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flood
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: flood
      version: 6.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: jesec/flood
      tag: 4.7.0
    env:
      FLOOD_OPTION_RUNDIR: /config
      FLOOD_OPTION_AUTH: "none"
      FLOOD_OPTION_RTSOCKET: "/config/.local/share/rtorrent/rtorrent.sock"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: &host "flood.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: "OnRootMismatch"
      supplementalGroups: [10000]
    persistence:
      config:
        enabled: true
        storageClass: "freenas-iscsi-csi"
        accessMode: ReadWriteOnce
        size: 10Gi
      data:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: /mnt/media
      socket:
        enabled: true
        type: emptyDir
        # medium: Memory
        mountPath: /tmp
      rtorrent-rc:
        enabled: true
        type: configMap
        name: rtorrent-flood-configmap
        subPath: rtorrent.rc
        mountPath: /etc/rtorrent.rc
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      readiness:
        enabled: true
        initialDelaySeconds: 30
        failureThreshold: 5
        timeoutSeconds: 10
      startup:
        enabled: true
        initialDelaySeconds: 5
        failureThreshold: 30
        periodSeconds: 10
    additionalContainers:
      - name: rtorrent
        image: jesec/rtorrent:latest
        env:
          - name: PUID
            value: "568"
          - name: PGID
            value: "568"
          - name: HOME
            value: "/config"
        livenessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        ports:
          - name: bt
            containerPort: 49161
            protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 50m
            memory: 200Mi
        startupProbe:
          failureThreshold: 60
          periodSeconds: 10
          initialDelaySeconds: 5
          successThreshold: 1
          tcpSocket:
            port: bt
          timeoutSeconds: 1
        tty: true
        volumeMounts:
          - mountPath: /config
            name: config
          - mountPath: /data
            name: data
          - mountPath: /session
            name: data
            subPath: .session
          - mountPath: /watch
            name: data
            subPath: watch
          - mountPath: /download
            name: data
            subPath: torrents
          - mountPath: /socket
            name: socket
          - mountPath: /etc/rtorrent.rc
            name: rtorrent-rc
    service:
      bt:
        enabled: true
        type: LoadBalancer
        ports:
          bt:
            enabled: true
            port: 49161
            protocol: TCP
            targetPort: 49161
