---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: rtorrent-flood-configmap
    files:
      - rtorrent.rc
