---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: democratic-csi-iscsi
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.5
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: false
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    csiDriver:
      name: org.democratic-csi.iscsi
    driver:
      config:
        driver: freenas-iscsi
        httpConnection:
          allowInsecure: true
          host: ${DEMOCRATIC_HOST}
          password: ${DEMOCRATIC_PASSWORD}
          port: 80
          protocol: http
          username: ${DEMOCRATIC_USERNAME}
          apiVersion: 2
        iscsi:
          namePrefix: csi-
          nameSuffix: -cluster-00
          extentRpm: 7200
          targetGroups:
            - targetGroupAuthType: None
              targetGroupInitiatorGroup: 1
              targetGroupPortalGroup: 1
          targetPortal: ${DEMOCRATIC_HOST}:3260
          targetPortals: []
        sshConnection:
          host: ${DEMOCRATIC_HOST}
          password: ${DEMOCRATIC_PASSWORD}
          port: 22
          username: ${DEMOCRATIC_USERNAME}
        zfs:
          datasetParentName: pool-01/k8s/vols
          detachedSnapshotsDatasetParentName: pool-01/k8s/snapshots
    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""
    storageClasses:
      - allowVolumeExpansion: true
        defaultClass: true
        mountOptions: []
        name: freenas-iscsi-csi
        parameters:
          fsType: ext4
        volumeBindingMode: Immediate
    volumeSnapshotClasses: []
