---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: recyclarr-configmap
    files:
      - ./recyclarr.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
labels:
  - pairs:
      app.kubernetes.io/name: recyclarr
      app.kubernetes.io/instance: recyclarr
