apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
    namespace: media
type: Opaque
stringData:
    RADARR__API_KEY: ENC[AES256_GCM,data:vwboOOC5sXg6NKAf+NHIFkop6DMB7h/nS93rvXK9H/A=,iv:rVdt10o/Y3pF1fOzKaRTkYtQ4PE1Hmxp77C6sk6xSro=,tag:2p/mqlxbxhT20Vvef/d2tw==,type:str]
    RADARR_ANIME__API_KEY: ENC[AES256_GCM,data:xlpdInPHJbm+Ud9mC7dGkA/XPpWKJwgW4H2++67Yk58=,iv:BP7WHDI3X/ztgh4VwMIOsbmdUiPT09dKhuManbvikKE=,tag:ZnXxMSf2NOXjNp5AaUdCFg==,type:str]
    SONARR__API_KEY: ENC[AES256_GCM,data:xPQ4CBsLm5/O3Opg6rBW4kh1Y+9WlyDoNjERWhYC7og=,iv:VvumRMGClKKK/U5e2vhzVF636/1dgwqBL+D6QFiBsiE=,tag:efUUnaUbc1y4fMSOlT25tA==,type:str]
    SONARR_ANIME__API_KEY: ENC[AES256_GCM,data:M7oZTUXfCTtdTg18c2457D73x/Z/pf9Y75VLoLZoCjs=,iv:MXNGOGWRu5SCwakYWc1qIaWAnnVkRKYRrTOyIvHSn6A=,tag:PRToi8CwP9eJS/F2L+Ji1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVWcxT3F6UkVDSTRlbUxm
            VysxWklrNGJpdVRtNURBaHkrQXN6T2RGNDFjCnZyWFhvR2p1NXNuKy9OVWJLdnJ3
            cFFiN1NVWjlSN2x5clEyUzFjc0VPczQKLS0tIEs0ZzlBQVJwSTV3TGdOMVRleVh0
            UmVkR01kYmJSUlZ5NjFSc1RFRnRuZXcKlL6ib4F0ZysFC0eAf9yW2t+pG0gSItKz
            3KIoLx/qQ42VbZjYT3zzn6p8KK8kIhzraO2fzM+2TSihFN7IyAf87A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-07T08:51:49Z"
    mac: ENC[AES256_GCM,data:dJa0DEU3r+QxlVHkul6mxCH/bBESFIMzUoeSPEYbvNdVuuW7aPJOvWyMoTUggh0OAzfDg4ZXwUYtyjZJtzxEmAN6aldhennC4qraz464V+i3jCgIwVp7Fi13+mqjtwWSjep0WriQP1Oq7ww2ZaKIOXdS86HnO5xLjCLAt3y1iU0=,iv:ORzBV6Z3gtN6t6/zCKcGqOnSgEq1k2vRiTKlwvfVOQ8=,tag:TVD5qglGmfQtMaJy3Lxt2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
