apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:sXJdpI1INK4NOEBmCie9i7kP,iv:yyfktQIjM0VCU3Z484hTrgsD/p2DhwenG4mTtyeM0i8=,tag:JnduJZH2EF3OLQLxCmVGAg==,type:str]
    api-key: ENC[AES256_GCM,data:E8UbY0Gx7th7a1HdMGz0bPDVlYrOV3zr2SVbzZi2No1D/oyqDw==,iv:sDpIyXNhVgv3zN796ZeEbGpYw/SGItgDeUpkrZsp4Rw=,tag:HS2RIqj5/5g9uEUHjgQTpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYT1hBQnFxTTg5bGU4MFNy
            NTBaUlh6Q0MvenhCa2l3VTNCSmlCR24wcEFzCjFOZ0IrNHZINzhrdHA5VFBuWVBl
            b3VJTC9IdW8rRFU3SytLZG82YVpSWWcKLS0tIExPWE91cG00WUYxRXRZczhHTTBQ
            bUpaRXB2QUF4RjVVa3JGTytOWE5ZTGMKHz2X1b3PmzJVcJp/diAqIbGOLSs45Nbn
            hYTxBLlBO/4B41bZuhFX3fH45eSfjdD9ZbrdVyQIbLGzy6x9eISGjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T01:27:03Z"
    mac: ENC[AES256_GCM,data:V1/NCB7D8LfJjOVPr4orC+FYHso0KVwPGMdz7+OxUqrJ8jpQWN16pXlg1u+SWSgQAB2VmQNphGGl9CzzEsO3Ulb+XM9XcQC5jv+4wFvcUZlBUohW4MmfPwwdFLD+KNe7CZBZh8mViqNYgGrXiqdSgC5J5RoRq9xdiPmyQkxI4GM=,iv:jQYVf6SS6caV09didQjwopjLGuDqEA9lBnyVk0F+XwE=,tag:L8wSK7heBNEeR045dHTNvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
