---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-radarr2
  namespace: flux-system
spec:
  path: ./kubernetes/apps/media/radarr2/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: radarr2
      namespace: media
  interval: 30m
  retryInterval: 1m
  timeout: 3m
