apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:cp6cv0cIVUew5tRRirMZfQURcWtbtX7xqbsjte+cDYCKrnkNtPRd54ijjs7oi4O29yIcr9i3JOX5pDRU,iv:mkSCnvaFfPflRWYgEmm6Kk6XsPgc9IMjTiEBbUuIVKg=,tag:Mok+6UNgvVykPgfHX6EznQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5TC9VSTNCek5mSVlySXR2
            OW1GYm9Rb01MK1MrZDFLT0VtQXgxRy9weW1jCjM0L3MxckV2TWhMbzNXTnNCdHZW
            MVVNRElrOG5SaGVSN0Mrd1ZiTVFoU2MKLS0tIEorYjYvZmpRbFd6VkRDakdIeE5D
            UjVDdFlhN01JSzFiWmVOejN0R2tYL28Kw3gkeiHcTVxkOUQ+w68F/8tkO7Ij7jRd
            iCOIL3W2hHBTFHuDfmjI9g0qGFMiK04vF6TUMrFvW01pKvBsbwXYaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T01:27:04Z"
    mac: ENC[AES256_GCM,data:rRND7SFFGo5sywwMqUzeC/zf1pxBOeJ/u1NW9YjYbx2tpka/vzL7+wWQCvixBBrOpDrxEJ0eGZBL4bHnwVcKtO7dDkuhocm41dCVew2wF3FChlADqvMMXme/5CrMuV3qQy9w59jHflizr1xbUZ+NtiGirmN8JZrwJn3GIriaRLc=,iv:hjMEMWgSW2ktgep+s1wfaa0/xJuZa9fGPRvfrEEVv8U=,tag:DrXygaTrbf/gFxtFGec25g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
