apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:oj33/RwRDXz1W0XAEp1jnGSQMtOu9FXP0x19UQMZvsNMhRYt4ZFOonA8PWiJIvkWvOycTzwTxVwpwyUV,iv:mBlcW7QmQFHmhWvD6MODGDL6LAFOQOWTJYlepo0N7CU=,tag:palUL62x2IMCUjpgGwAVFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBldFMwT3FRbnNKWXF2bnlX
            WEJGOC9neUlrc2JTTVhpdDJtdCs5bnpsNFVrCkRCKzJibEE3ZlBreFVoVXlCdUJq
            dDdKM2dISyt6V0pmNmk4ZmR4SmY2VzAKLS0tIEVDUlZpUDNBZkRsWTd5bk5uWW1N
            VEVadGVNYjkvMnVmS0RTZThIOG4wUVEKJzM6I8aOdnUzMvDq9mIZ/R9MR+DboDoo
            iqg9bgEXgM6ZM/0B+6+k0oW1wpc1aP+I670+pa7sby+IEsIsSfLARg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-01T09:11:36Z"
    mac: ENC[AES256_GCM,data:/8aOVjAFnmo77zdwisbiJgMURFeUjD+hX36v/85/88af1b4d6hWXWLv3lUEr50NyUOoPG3/SRqskJhxYrbN/gre5dFsubicUtGnKuFO0mOo68HDPJfJ56/9kZZX02dUvs6Rw3uqUzwhYwXwlaw+DwroBScenYYzRLUNeVFxrXzY=,iv:3jzxTHt1B6KqrttHI36fVnuq/6H6/E9kRq9SJDcqL3I=,tag:F8GUVtBRg7Zvu3lpEbIp/A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
