---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: admin
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.2.3
      sourceRef:
        kind: HelmRepository
        name: goauthentik
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/goauthentik/server
      tag: 2023.2.3
    envFrom:
      - secretRef:
          name: authentik-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: &host "authentik.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    postgresql:
      enabled: true
      existingSecret: "authentik-postgres-secret"
      persistence:
        enabled: true
        storageClass: "freenas-iscsi-csi"
        size: 8Gi
    redis:
      enabled: true
      architecture: replication
      auth:
        enabled: false
      persistence:
        enabled: true
        path: /data
        storageClass: "freenas-iscsi-csi"
        size: 8Gi
