apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:N4PkqOUzih8dYIV5sw==,iv:hXsJceD9MZzjteyw1GFZZfb2NKFUzJ9bcVBfKgvyRdU=,tag:hcQuRp73y6lKK3urGm84RQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:+8ok9kfMXfXu3XTbjhc5q4/h,iv:PrWd8nC/GLFN13h1ZULVYlylKfJi5n6ol9itgaxGgR4=,tag:wcEZ2MoqomV5AfSIhk4pcw==,type:str]
    DEMOCRATIC_USERNAME: ENC[AES256_GCM,data:lixh/A==,iv:N0uoecgvdgheww7ea8CIcPbV7Pm/zmQ68lJ1SuS4cIk=,tag:8a6haH+pMbsHZwZpbEcjMw==,type:str]
    DEMOCRATIC_PASSWORD: ENC[AES256_GCM,data:Me3LIRMjsxIENGG48f06,iv:ScWjiaD8CCiikgeBwQ+MnDUOqYB/awVyxam167r0yhI=,tag:ZOm5IftdSXoTJr4z4g1ZTw==,type:str]
    DEMOCRATIC_HOST: ENC[AES256_GCM,data:rysox8lhOwNI9Dakag==,iv:aKRhSsYwcOAh3sA3o4EwbI5xiGiA1qxK2HzOjomKDgU=,tag:zwASQWRLujv2hLlIlQV8CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPclNMWEFqeFlKeDQwTXJx
            MjdETFlhQlRMWVQ0UHJSd0NEMVlmMXpua21NCjR0cmpYcEhHakVzSG91bklSTUpl
            RVRZMkd0MHRobGI4UXY5ZnQvT2NTTVEKLS0tIHdSendrblpTZ1ZMN1lNdDFnMFdy
            VU40akNGQWxQcHV3cmx3MHlwNGkzRDAKayXARER68rGwUapwdtoPQPxnU7R8HyEr
            jKsoUyGESc3sLBu4KQe87YA8H1v4VMk3VaSDGqD+DZMs6A0Nnm0Qdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-04T01:27:03Z"
    mac: ENC[AES256_GCM,data:jayUnb1B81s93gEyMRa0/elLZTGGHvLKa5DgGmYdzJ/YLxovjYzSIazcRq2uSL9UrdQ3h6bq/SXOSTBXtfdBTY6knI18rreM1lKEoCr4mUIqLQ5+6+OL9DNnQ1cQ8g1Ht17nTZINsB/ytDLboc+g6T3rqS8WuL6StoWI1xdLlZ8=,iv:5qE67ygRByK7ke9x9Fv7ZgotmNtoKDo9OkSFPX19JoA=,tag:q2M3J00qABVfvBPMNmjlIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
