apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:x+lJZqrDRTruAxVWmQ==,iv:qNN+O8+6aMUR5pU5QzCovRnIqp+PL5ivL+ukyKEt5Zc=,tag:i/HaXIIvq3gdgWyl1U28uA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SrxvHukOuFrB7I/HBabPQFUq,iv:/FpOe2ws+QC5VUPOBGdnZ68ZgN4CQ+TupdJ+yv7G2Og=,tag:V1eeMRa4KeFCHSLZDtqk0A==,type:str]
    DEMOCRATIC_USERNAME: ENC[AES256_GCM,data:hH9RnQ==,iv:81iecAGZ6ER7Ftumj93knvScUhxeFqTprEEByv0MovY=,tag:oXlxakBZtsElu2L4eeDGVQ==,type:str]
    DEMOCRATIC_PASSWORD: ENC[AES256_GCM,data:kfS6Wtq6Um3FrnjwsIU2,iv:0ff13hUWRIdaA5Lu/NTnbUSZD2LfdH0Zc1p5+uWnPpY=,tag:sGfnPLB+tf/jl9RjDnQ1XA==,type:str]
    DEMOCRATIC_HOST: ENC[AES256_GCM,data:J/ulUVio+md32+mN6g==,iv:W/sDPtNdigrWNDhpY9PobfohTWiJS+OkvQ5e/kTV62w=,tag:fOZPWKbjqOb5c70IPTHQow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tcxgqkt46vx0khyjxv88agewx350dv7tgqfr526456dmjacpveest9ncdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6U0JhRGE4dHBMVUJleWZm
            ampGUFhJOG91dmp1UFh6dU5YR0lvYnNyTGpvCm9OMUU1bFRuWXRJcE94VGRxb3pn
            OFVJYVNzRUlJaVBSRGtPOEN1Y201bGsKLS0tIHpWVTVOcmY4dW02eHZoY2VHMkdG
            KzRRRW1wTHdaVEZPdjhwMGdGZWttY1kKPk8Faz/tLHgtssTSyMEs8pk043jsUxha
            dnoffTzeC5UFazjjXdRW65+Bx5WoIPkz5i2J0ydbDfMllqZCTanSOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-02T06:27:58Z"
    mac: ENC[AES256_GCM,data:WCmmoySI8XJf+pSUuj82z/xGEkzUTmHUBpz6tlcvc/YFvaNCrjCp+2wRSStObcX425hOoP5kI1/b0e02KU+f66WcJ6asx4mP9m2KGfiMdpoDrzncuNucJSwE9Z2DKwSZcYrrgcOFdbgDaBoqrU5XCzeFiEnmZvYYd9McehjpcOQ=,iv:S+W8eZNc2FWqduBiy17KRPB9mDUx4cLChd/7yymCCWo=,tag:QnFlwUWb8jXiFaavcxBFow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
