---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    image:
      repository: ghcr.io/linuxserver/plex
      tag: 1.31.0
    env:
      VERSION: docker
      TZ: "America/New_York"
      DOCKER_MODS: "ghcr.io/pabloromeo/clusterplex_dockermod:latest"
      ORCHESTRATOR_URL: "http://clusterplex-orchestrator:3500"
      PMS_IP: "10.99.66.38"
      PMS_PORT: "32400"
      TRANSCODER_VERBOSE: "1"
      TRANSCODE_OPERATING_MODE: both
      LOCAL_RELAY_ENABLED: "0"
      LOCAL_RELAY_PORT: "32499"
    service:
      main:
        type: LoadBalancer
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/allow-shared-ip: plex
        port:
          port: 32400
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: &host "channel.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podLabels:
      app.kubernetes.io/part-of: clusterplex
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: clusterplex-worker
              topologyKey: kubernetes.io/hostname
            weight: 50
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  name: plex
              topologyKey: kubernetes.io/hostname
            weight: 100
    persistence:
      config:
        enabled: true
        storageClass: "freenas-iscsi-csi"
        accessMode: ReadWriteOnce
        size: 135Gi
      transcode:
        enabled: true
        existingClaim: clusterplex-transcode-pvc
        mountPath: /transcode
        readOnly: false
      tmp:
        enabled: true
        type: emptyDir
        medium: Memory
      nfs-media-pvc:
        enabled: true
        existingClaim: nfs-media-pvc
        mountPath: /mnt/media
        readOnly: false
    resources:
      requests:
        cpu: 12
