---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cluster-apps-democratic-csi-iscsi
  namespace: flux-system
spec:
  path: ./kubernetes/apps/kube-system/democratic-csi-iscsi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: democratic-csi-iscsi
      namespace: kube-system
  interval: 30m
  retryInterval: 1m
  timeout: 3m
