---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: "${BOOTSTRAP_CLOUDFLARE_DOMAIN}"
  SECRET_DOMAIN_2: "${BOOTSTRAP_CLOUDFLARE_DOMAIN_2}"
  SECRET_CLOUDFLARE_EMAIL: "${BOOTSTRAP_CLOUDFLARE_EMAIL}"
  DEMOCRATIC_USERNAME: "${BOOTSTRAP_DEMOCRATIC_USERNAME}"
  DEMOCRATIC_PASSWORD: "${BOOTSTRAP_DEMOCRATIC_PASSWORD}"
  DEMOCRATIC_HOST: "${BOOTSTRAP_DEMOCRATIC_HOST}"
